name: Update emplois data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_emplois:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade duckdb pandas

      - name: Download data
        run: |
          wget -O offres_demploi.parquet "https://data.gouv.nc/api/explore/v2.1/catalog/datasets/offres-demploi/exports/parquet?lang=fr&timezone=Pacific%2FNoumea"

      - name: Execute script
        run: |
          python - <<EOF
          import duckdb

          con = duckdb.connect(database='emploi-nc.duckdb', read_only=False)
          con.sql("""create or replace temp table load_emploi as select * from 'offres_demploi.parquet'""")

          con.sql("""create or replace table emplois as select
              coderome,
              apourvoirle as a_pourvoir_le,
              titreoffre as titre_offre,
              datepublication as date_publication,
              case when (desquepossible = 1) then 'Dès que possible' else '' end as des_que_possible_desc,
              diplome,
              duree || ' ' || uniteduree as duree_contrat,
              nbpostes as nb_postes,
              numero,
              created,
              niveauformation as niveau_formation,
              experience,
              communeemploi as commune_emploi,
              employeur_nomentreprise as employeur_nom_entreprise,
              employeur_adressecorrespondance_subdivision as employeur_adresse_correspondance_subdivision,
              activites_multivalue,
              competences_multivalue,
              contact_mail
          from load_emploi
          where statut = 'PUBLIEE'""")

          con.sql("""COPY emplois TO 'data/emplois.csv' (FORMAT csv, DELIMITER ',', HEADER)""")
          EOF

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "adriens"
          git config --global user.email "adrien.sales@gmail.com"
          git add data/emplois.csv
          git commit -m "Ajout ou mise à jour de data/emplois.csv"
          git push origin main
